secrets: secrets.yml

templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.user }}'
      password: '{{ secrets.transmission.password }}'

    email:
      active: True
      template: html
      from: '{{ secrets.mail.from }}'
      to: '{{ secrets.mail.to }}'
      smtp_host: localhost
      smtp_port: 25
      smtp_login: False

  movies:
    imdb:
      min_score: 5.0
      min_votes: 5000
    download: '{{ secrets.path.movies }}'

    transmission:
      path: '{{ secrets.path.movies }}'

    content_filter:
      require: "*.mkv"

    regexp:
      reject:
        - hindi
        - german
        - spanish
        - YIFY
      accept:
        - SPARKS
        - publicHD
        - rarbg
    imdb_required: yes
    seen_movies: strict
    content_size:
      min: 6000
      max: 26000
    quality:
      - 1080p+ bluray remux

  tv:
    exists_series: '{{ secrets.path.series }}'

    transmission:
      path: '{{ secret.path.series }}/{{ series_name|replace(":"," -") }}/Season {{ series_season }}'

    regexp:
      reject:
        - www.Speed.Cd
        - www.Torrenting.com

    content_filter:
      reject: '*.rar'

    series:
      settings:
        tvshows:
          timeframe: 2 hours
          quality: 1080p
          upgrade: yes
          set:
            path: '{{ secret.path.series }}/{{ series_name|replace(":"," -") }}/Season {{ series_season }}'
      tvshows:
        - House
        - How I Met Your Mother
        - The Big Bang Theory
        - Downton Abbey
        - Game of Thrones
        - Lie to Me
        - Star Trek
        - Leverage
        - Stargate
        - Fringe
        - Castle 2009
        - NCIS
        - CSI Miami
        - CSI New York
        - Dexter
        - South Park
        - 'CSI'
        - Supernatural
        - Bones
        - Person of Interest
        - Top Gear
        - Sherlock
        - The Following
        - The Killing
        - The Mentalist
        - Futurama
        - Chuck
        - Life
        - Eureka
        - The Walking Dead
        - Arrow
        - Criminal Minds
        - Doctor Who
        - Cold Case
        - The Daily Show
        - Agatha Christies Poirot
        - suits

tasks:
  EzRss:
    rss: http://www.ezrss.it/feed/
    template: tv
    priority: 10
  EzRsss_FeedBurner:
    rss: http://feeds.feedburner.com/eztv-rss-atom-feeds?format=xml
    template: tv
    priority: 11
  TPB_Series_HD:
    rss: http://rss.thepiratebay.se/208
    template: tv
    priority: 20
  TPB_Movies_HD:
    rss: http://rss.thepiratebay.se/207
    template: movies
