variables: secrets.yml

templates:
  global:
    include: global.yml

    transmission:
      host: localhost
      port: 9091
      username: '{? transmission.user ?}'
      password: '{? transmission.password ?}'

    notify:
      task:
        template: default
        via:
          - email:
              from: '{? mail.from ?}'
              to: '{? mail.to ?}'
              smtp_host: localhost
              smtp_port: 25

  tv:
    urlrewrite:
      sitename:
        regexp: 'http:\/\/torcache\.net\/torrent\/(?P<id>.*)\.torrent\?title=(?P<title>.*)'
        format: 'http://torcache.net/torrent/\g<id>.torrent'

    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
      Referer: "http://torcache.net/"
      Accept-Encoding: "deflate, gzip"

    magnets: yes
    thetvdb_lookup: yes

    transmission:
      path: '/home/shared/series/{{ series_name|replace(":"," -") }}/Season {{ series_season }}'

    exists_series:
      - '{? path.series ?}'

  movies:
    include: movies_conf.yml

    transmission:
      path: '{? path.movies ?}'
    download: '{? path.movies ?}'

tasks:
  TV_Shows:
    inputs:
      - rss: '{? input.series ?}'
    include: series.yml
    template:
      - tv

  Movies_2160p:
    priority: 1
    inputs:
      - rss: '{? input.movies ?}'
    template:
      - movies
    quality: 2160p+

  Movies_1080p:
    priority: 2
    inputs:
      - rss: '{? input.movies ?}'
    template:
      - movies
    quality: 1080p+
    delay: 5 hours
