transmission:
  user: <user>
  password: <password>

mail:
  from: <email>
  to: <email>

path:
  animes: <anime_path>
  movies: <movies_path>
  series: <series_path>

input:
  series: https://thebestoflinuxdistoshows.com/rss
  movies: https://theultimateopensourcesmovies.com/rss
