# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

alias "l=ls -l"
alias "la=ls -la"
alias "emacs=emacs -nw"
alias "ne=emacs"
alias "sbl=sublime"
alias "clearswap=su -c 'swapoff -a && swapon -a'"

PATH=$PATH:$HOME/Applications/bin #Add custom bin path
PATH=$PATH:$HOME/.local/bin:$HOME/bin