# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

alias "l=ls -l"
alias "la=ls -la"
alias "emacs=emacs -nw"
alias "ne=emacs"
alias "sbl=sublime"
alias "clearswap=su -c 'swapoff -a && swapon -a'"
alias "mountfreenas=sshfs freenas.local:/mnt/vol1 ~/mnt/freenas"

PATH=$PATH:$HOME/Applications/bin #Add custom bin path
PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH="$HOME/.rbenv/bin:$PATH"
export ANDROID_HOME=$HOME/Sdk/Android/sdk
export JAVA_HOME="/etc/alternatives/java_sdk"
export LC_ALL=en_US.UTF-8

if [ -d "$HOME/.rbenv" ]; then
   eval "$(rbenv init -)"
fi
